<a href="https://colab.research.google.com/github/prethasur/tutorials/blob/main/pyTorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://download.pytorch.org/whl/cu116


In [5]:
import torch

##initializing tensors

In [17]:
device= "cuda" if torch.cuda.is_available() else "cpu"

In [20]:
#when you know the values
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [22]:
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.requires_grad)

cuda:0
torch.Size([2, 3])
torch.float32
False


In [23]:
garbage_tensor = torch.empty((3,3)) #creates a tensor of the said shape, but with garbage value exinsting in memory
print(garbage_tensor)

tensor([[2.1715e-18, 2.3081e-12, 1.8590e+34],
        [7.7767e+31, 1.7181e+19, 1.8990e+28],
        [1.5766e-19, 1.4585e-19, 7.1856e+22]])


In [25]:
zero_tensor=torch.zeros((3,3))
print(zero_tensor)
#same for torch.ones - 11111111

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [26]:
rand_tensor=torch.rand((3,3))
print(rand_tensor)

tensor([[0.2574, 0.1368, 0.9879],
        [0.1213, 0.1315, 0.6510],
        [0.4548, 0.5182, 0.1744]])


In [28]:
id_tensor=torch.eye(3,3)
print(id_tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [34]:
range_tensor=torch.arange(start=0, end= 10, step=2) #like range
print(range_tensor)

tensor([0, 2, 4, 6, 8])
