<a href="https://colab.research.google.com/github/prethasur/tutorials/blob/main/pyTorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://download.pytorch.org/whl/cu116


In [1]:
import torch

##initializing tensors

In [2]:
device= "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
#when you know the values
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [ ]:
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.requires_grad)

cuda:0
torch.Size([2, 3])
torch.float32
False


In [ ]:
garbage_tensor = torch.empty((3,3)) #creates a tensor of the said shape, but with garbage value exinsting in memory
print(garbage_tensor)

tensor([[2.1715e-18, 2.3081e-12, 1.8590e+34],
        [7.7767e+31, 1.7181e+19, 1.8990e+28],
        [1.5766e-19, 1.4585e-19, 7.1856e+22]])


In [ ]:
zero_tensor=torch.zeros((3,3))
print(zero_tensor)
#same for torch.ones - 11111111

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
rand_tensor=torch.rand((3,3))
print(rand_tensor)

tensor([[0.2574, 0.1368, 0.9879],
        [0.1213, 0.1315, 0.6510],
        [0.4548, 0.5182, 0.1744]])


In [ ]:
id_tensor=torch.eye(3,3)
print(id_tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
range_tensor=torch.arange(start=0, end= 10, step=2) #like range
print(range_tensor)

tensor([0, 2, 4, 6, 8])


In [ ]:
lin_tensor=torch.linspace(start=0.1, end=0.5, steps=10)
print(lin_tensor)

tensor([0.1000, 0.1444, 0.1889, 0.2333, 0.2778, 0.3222, 0.3667, 0.4111, 0.4556,
        0.5000])


In [ ]:
norm_tensor=torch.empty(1,10).normal_(mean=0, std=1) #can be for uniform distribution, log normal and others
print(norm_tensor)

tensor([[-0.1060,  0.4130,  0.4076, -1.4723,  0.6186, -1.3502,  1.0230, -0.4322,
          0.6122, -0.4888]])


In [ ]:
diag_tensor=torch.diag(torch.rand(3)) # multiples identity matrix to the given tensor
print(diag_tensor)

tensor([[0.9754, 0.0000, 0.0000],
        [0.0000, 0.1168, 0.0000],
        [0.0000, 0.0000, 0.1673]])



##conversion to other types

In [ ]:
x=torch.arange(10) #by default start is 0, step is 1

###data types

In [ ]:
print(
    x.bool(), '\n',
    x.short(), '\n', #int16
    x.long(), '\n', #int64
    x.float() #float32
)

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True]) 
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16) 
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


###to numpy array and vice versa

In [ ]:
import numpy as np
np_array=np.zeros((3,3))
tensor=torch.from_numpy(np_array)
print (np_array, '\n', tensor)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [ ]:
np_back = tensor.numpy()
print(np_back)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##arithmatic & logical operations

In [ ]:
#add
x= torch.tensor([1,2,3])
y= torch.tensor([9,8,7])
z= torch.add(x,y) # or just z= x+y
print(z)

tensor([10, 10, 10])


In [ ]:
# substract
z=x-y
print(z)

tensor([-8, -6, -4])


In [ ]:
# division
z= torch.true_division(x,y) #elementwise division if x and y are of same shape

###inplace operations
they always have an -(underscore)

In [ ]:
t=torch.zeros([3,3])

In [ ]:
t.add_(x)
print(t)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])


###matrix multiplication

In [ ]:
x1=torch.rand(2,3)
x2=torch.rand(3,5)
x3=torch.mm(x1,x2) #2x5
print(x3)

tensor([[0.5147, 1.0088, 0.9383, 0.3045, 0.5336],
        [0.1824, 0.6290, 0.4186, 0.1378, 0.2911]])


In [ ]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm (tensor1, tensor2) # (batch, n, p)
# Example of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z = x1 - x2
z = x1 ** x2
# Other useful tensor operations 
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=8)
values, indices = torch.min(x, dim=8)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=8)
z = torch.eq(x, y)|

In [ ]:
sorted_y=torch.sort(y,dim=0, descending=False)
z=torch.clamp(x,min=0,max=10) #all values outside 0 to 10 will be made 0

###indexing

In [4]:
batch_size=10
features=25
x=torch.rand((batch_size, features))

print(x[0].shape)
print(x[:,0].shape)
print(x[2,0:10]) #3rd row, 0 to 10 cols

torch.Size([25])
torch.Size([10])
tensor([0.1537, 0.3024, 0.4621, 0.0962, 0.7080, 0.8161, 0.5329, 0.5000, 0.5683,
        0.0653])


In [8]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) & (x > 8)])
print(x[x.remainder(2)==0])


tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [9]:
# Useful operations 
print(torch.where(x > 5, x, x*2))
print(torch.tensor ([0,0,1,2,2,3,4]).unique()) 
print(x.ndimension())  
print(x.numel()) #number of elements

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


In [14]:
#Tensor Reshaping
x = torch.arange(9)
x_3x3 = x.view(3, 3)
print(x_3x3)
x_3x3 = x.reshape(3, 3)
y = x_3x3.t() 
print(y)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [15]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)
z = x1.view(-1) #flattens the whole thing
print(z.shape)
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1) #flattens the whole thing preserving batch dimension
print(z.shape)

torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([64, 10])


In [21]:
z = torch.rand(2,3,2) 
print(z.shape)
x = torch.arange(10) # [10]
print(x.shape)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1x1x10
print(x.shape)
z = x.squeeze(1)
print(z.shape)

torch.Size([2, 3, 2])
torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
torch.Size([1, 10])
